set_license('LGPL-3.0')
add_rules('mode.debug', 'mode.release')
add_requires('objfw 1.4.1')

target('omsfw')
  set_kind('static')
  add_packages('objfw')
  add_files('src/*.mm')
  add_includedirs('include')
  add_headerfiles('include/*.h')
