set_license('LGPL-3.0')
add_rules('mode.debug', 'mode.release')
add_requires('objfw 1.4.1')

target('omsfw')
  set_kind('static')
  add_packages('objfw', {public = true})
  add_files('src/*.mm')
  add_includedirs('include', {public = true})
  add_headerfiles('include/*.h')

target('omsfw-example')
  set_kind('binary')
  add_packages('objfw')
  add_deps('omsfw')
  add_files('example/src/*.mm', 'example/src/*.m')
  add_includedirs('example/src/include')
